FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1


RUN apt-get update
# установка pip
RUN pip install --upgrade pip

# назначение рабочей дирректории
WORKDIR /app

# копирование и установка requirements.txt
COPY ./requirements.txt /app/
RUN pip install -r requirements.txt

# Копируем исходный код приложения
COPY . .

# Команда для запуска FastAPI приложения
CMD ["python", "client.py"]